### ISSUE TITLE
Create RADE project team logins for DE

### ISSUE THREAD

**Issue by wclenhardt** [ResearchSoftwareInstitute/roi-rade#1]
Need DE logins for co-I's on project:

- Lenhardt
- Blanton
- Schmitt (may need to change after Charles starts @ NEIHS
- Dietrich
- Thill

**Comment by wclenhardt** [comment]
Lisa, I created this a while ago, but somehow I didn't get you added.  I believe this is completed, yes?

Thanks.

**Comment by lstillwe** [comment]
All accounts have been created and the account holders have been notified with their account id and password. Did not create account for Charles since he has already departed, and added and account for Ayse Karanci
